### ISSUE TITLE
Is there a way to detect / be notified when the web view is loaded?

### ISSUE THREAD

**Issue by liviavinci** [formidable-webview/webshell#12]
Is there a way to detect / be notified when the web view is loaded?

**Comment by jsamr** [comment]
All props available to WebView are available to Webshell. You can use for instance [`onLoad`](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onload) (although it's kind of ill-defined). If you mean "when the DOM is loaded", you could write up [a custom feature](https://formidable-webview.github.io/webshell/docs/implementing-features) that reports [`load` events](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event).

**Comment by liviavinci** [comment]
@jsamr thanks a lot!
