### ISSUE TITLE
Attempting to change configurable attribute of unconfigurable property.

### ISSUE THREAD

**Issue by zyslife** [formidable-webview/webshell#3]
If you're running on ios9, you're going to crash.
Attempting to change configurable attribute of unconfigurable property.

**Comment by jsamr** [comment]
@zyslife Thanks for the report, I am investigating right now.

**Comment by jsamr** [comment]
@zyslife I think I know where the error came from, although couldn't test with an iOS 9 device. This should be fixed in @formidable-webview/webshell@2.0.2. Could you please test and give me feedback?

**Comment by zyslife** [comment]
The problem has been solved. thank you.

**Comment by jsamr** [comment]
@zyslife Great! I'm glad it worked out. Don't hesitate if you have other reports.
